export const timetable_weekdays = [
                   {line: '113', destination: 'Tapiola (M)', time: '05:44'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '05:52'},

                   {line: '113', destination: 'Tapiola (M)', time: '06:15'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '06:21'},
                   {line: '113', destination: 'Tapiola (M)', time: '06:31'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '06:37'},
                   {line: '113', destination: 'Tapiola (M)', time: '06:46'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '06:49'},
                   {line: '113', destination: 'Tapiola (M)', time: '06:56'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '06:59'},

                   {line: '113', destination: 'Tapiola (M)', time: '07:07'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:10'},
                   {line: '113', destination: 'Tapiola (M)', time: '07:19'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:22'},
                   {line: '113', destination: 'Tapiola (M)', time: '07:30'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:33'},
                   {line: '113', destination: 'Tapiola (M)', time: '07:41'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:44'},
                   {line: '113', destination: 'Tapiola (M)', time: '07:51'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:54'},

                   {line: '113', destination: 'Tapiola (M)', time: '08:02'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:05'},
                   {line: '113', destination: 'Tapiola (M)', time: '08:12'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:15'},
                   {line: '113', destination: 'Tapiola (M)', time: '08:22'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:24'},
                   {line: '113', destination: 'Tapiola (M)', time: '08:31'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:33'},
                   {line: '113', destination: 'Tapiola (M)', time: '08:40'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:43'},
                   {line: '113', destination: 'Tapiola (M)', time: '08:50'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:53'},

                   {line: '113', destination: 'Tapiola (M)', time: '09:00'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:03'},
                   {line: '113', destination: 'Tapiola (M)', time: '09:10'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:13'},
                   {line: '113', destination: 'Tapiola (M)', time: '09:19'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:27'},
                   {line: '113', destination: 'Tapiola (M)', time: '09:37'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '09:52'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '10:07'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '10:22'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '10:37'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '10:52'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '11:07'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '11:22'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '11:37'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '11:52'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '12:07'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '12:22'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '12:37'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '12:52'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '13:07'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '13:22'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '13:37'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '13:52'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '14:09'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:10'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:21'},
                   {line: '113', destination: 'Tapiola (M)', time: '14:24'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:31'},
                   {line: '113', destination: 'Tapiola (M)', time: '14:39'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:41'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:51'},
                   {line: '113', destination: 'Tapiola (M)', time: '14:54'},

                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:02'},
                   {line: '113', destination: 'Tapiola (M)', time: '15:08'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:12'},
                   {line: '113', destination: 'Tapiola (M)', time: '15:20'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:23'},
                   {line: '113', destination: 'Tapiola (M)', time: '15:30'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:33'},
                   {line: '113', destination: 'Tapiola (M)', time: '15:40'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:43'},
                   {line: '113', destination: 'Tapiola (M)', time: '15:50'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:53'},

                   {line: '113', destination: 'Tapiola (M)', time: '16:00'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:04'},
                   {line: '113', destination: 'Tapiola (M)', time: '16:11'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:14'},
                   {line: '113', destination: 'Tapiola (M)', time: '16:21'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:24'},
                   {line: '113', destination: 'Tapiola (M)', time: '16:31'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:34'},
                   {line: '113', destination: 'Tapiola (M)', time: '16:41'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:43'},
                   {line: '113', destination: 'Tapiola (M)', time: '16:50'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:53'},

                   {line: '113', destination: 'Tapiola (M)', time: '17:00'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:03'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:10'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:13'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:20'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:22'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:29'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:31'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:38'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:48'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:51'},
                   {line: '113', destination: 'Tapiola (M)', time: '17:58'},

                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:01'},
                   {line: '113', destination: 'Tapiola (M)', time: '18:08'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '18:17'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '18:34'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '18:50'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '19:05'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:10'},
                   {line: '113', destination: 'Tapiola (M)', time: '19:20'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:25'},
                   {line: '113', destination: 'Tapiola (M)', time: '19:35'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:40'},
                   {line: '113', destination: 'Tapiola (M)', time: '19:50'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:55'},

                   {line: '113', destination: 'Tapiola (M)', time: '20:05'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '20:20'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '20:35'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:41'},
                   {line: '113', destination: 'Tapiola (M)', time: '20:49'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:56'},

                   {line: '113', destination: 'Tapiola (M)', time: '21:03'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '21:11'},
                   {line: '113', destination: 'Tapiola (M)', time: '21:19'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '21:26'},
                   {line: '113', destination: 'Tapiola (M)', time: '21:34'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '21:40'},
                   {line: '113', destination: 'Tapiola (M)', time: '21:47'},

                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '22:04'},
                   {line: '113', destination: 'Tapiola (M)', time: '22:17'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '22:34'},
                   {line: '113', destination: 'Tapiola (M)', time: '22:47'},

                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '23:04'},
                   {line: '113', destination: 'Tapiola (M)', time: '23:17'},
                   {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '23:34'},
                   {line: '113', destination: 'Tapiola (M)', time: '23:47'},

                   {line: '113N', destination: 'Kamppi', time: '00:47'},

                   {line: '113N (pe)', destination: 'Kamppi', time: '01:47'},

                   {line: '113N (pe)', destination: 'Kamppi', time: '02:47'}

                 ];

export const timetable_saturdays = [];
export const timetable_sundays = [
                  {line: '113', destination: 'Tapiola (M)', time: '06:12'},
                  {line: '113', destination: 'Tapiola (M)', time: '06:42'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '06:54'},

                  {line: '113', destination: 'Tapiola (M)', time: '07:12'},
                  {line: '113', destination: 'Tapiola (M)', time: '07:42'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '07:54'},

                  {line: '113', destination: 'Tapiola (M)', time: '08:12'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:24'},
                  {line: '113', destination: 'Tapiola (M)', time: '08:42'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '08:54'},

                  {line: '113', destination: 'Tapiola (M)', time: '09:13'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:24'},
                  {line: '113', destination: 'Tapiola (M)', time: '09:43'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '09:50'},

                  {line: '113', destination: 'Tapiola (M)', time: '10:13'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '10:39'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '10:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '11:04'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '11:34'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '11:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '12:04'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '12:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '12:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '13:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '13:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '13:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '14:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '14:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '14:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '15:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '15:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '15:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '16:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '16:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '16:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '17:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '17:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '17:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '18:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '18:35'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '18:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '19:05'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '19:34'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '19:51'},

                  {line: '113', destination: 'Tapiola (M)', time: '20:04'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:21'},
                  {line: '113', destination: 'Tapiola (M)', time: '20:34'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '20:52'},

                  {line: '113', destination: 'Tapiola (M)', time: '21:17'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '21:32'},
                  {line: '113', destination: 'Tapiola (M)', time: '21:46'},

                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '22:04'},
                  {line: '113', destination: 'Tapiola (M)', time: '22:16'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '22:35'},
                  {line: '113', destination: 'Tapiola (M)', time: '22:46'},

                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '23:03'},
                  {line: '113', destination: 'Tapiola (M)', time: '23:16'},
                  {line: '111', destination: 'Hyljelahti via Tapiola (M)', time: '23:33'},
                  {line: '113', destination: 'Tapiola (M)', time: '23:47'},

];
